-- =============================================================================
-- ORACLE DATABASE SCHEMA
-- CRM Inventory & Misc Receipt Application
-- Converted from SQLite/Prisma schema
-- Compatible: Oracle Database 12c Release 2 (12.2) and above
-- =============================================================================
-- Run this script as the application schema owner (e.g. CRM_APP).
-- All objects are created in the current schema.
-- =============================================================================

-- ─── USERS ────────────────────────────────────────────────────────────────────

CREATE TABLE USERS (
  ID              NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMAIL           VARCHAR2(255)   NOT NULL,
  PASSWORD_HASH   VARCHAR2(255)   NOT NULL,
  ROLE            VARCHAR2(50)    DEFAULT 'USER'         NOT NULL,
  IS_ACTIVE       NUMBER(1)       DEFAULT 1              NOT NULL,
  CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP   NOT NULL,
  UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP   NOT NULL,
  CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
  CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('ADMIN', 'MANAGER', 'USER')),
  CONSTRAINT CK_USERS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE OR REPLACE TRIGGER TRG_USERS_UPD
  BEFORE UPDATE ON USERS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- ─── ACTIVITY_LOGS ────────────────────────────────────────────────────────────

CREATE TABLE ACTIVITY_LOGS (
  ID              NUMBER(10)      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID         NUMBER(10)      NOT NULL,
  ACTION_TYPE     VARCHAR2(100)   NOT NULL,
  ACTION_DETAILS  CLOB,
  IP_ADDRESS      VARCHAR2(100),
  CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP   NOT NULL,
  CONSTRAINT FK_ACTLOGS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_ACTLOGS_USER_ID  ON ACTIVITY_LOGS (USER_ID);
CREATE INDEX IDX_ACTLOGS_CREATED  ON ACTIVITY_LOGS (CREATED_AT);

-- ─── INVENTORY_UPLOADS ────────────────────────────────────────────────────────

CREATE TABLE INVENTORY_UPLOADS (
  ID                NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID           NUMBER(10)    NOT NULL,
  FILENAME          VARCHAR2(500) NOT NULL,
  ORGANIZATION_NAME VARCHAR2(500) DEFAULT '',
  TOTAL_RECORDS     NUMBER(10)    DEFAULT 0  NOT NULL,
  SUCCESS_COUNT     NUMBER(10)    DEFAULT 0  NOT NULL,
  FAILURE_COUNT     NUMBER(10)    DEFAULT 0  NOT NULL,
  STATUS            VARCHAR2(50)  DEFAULT 'PENDING' NOT NULL,
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INVUP_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_INVUP_USER_ID  ON INVENTORY_UPLOADS (USER_ID);
CREATE INDEX IDX_INVUP_STATUS   ON INVENTORY_UPLOADS (STATUS);
CREATE INDEX IDX_INVUP_CREATED  ON INVENTORY_UPLOADS (CREATED_AT);

-- ─── INVENTORY_SUCCESS_RECORDS ────────────────────────────────────────────────

CREATE TABLE INVENTORY_SUCCESS_RECORDS (
  ID              NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  UPLOAD_ID       NUMBER(10)    NOT NULL,
  ROW_NUMBER      NUMBER(10)    NOT NULL,
  RAW_DATA        CLOB,
  RESPONSE_BODY   CLOB,
  RESPONSE_STATUS NUMBER(10),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INVSUC_UPLOAD FOREIGN KEY (UPLOAD_ID) REFERENCES INVENTORY_UPLOADS (ID)
);

CREATE INDEX IDX_INVSUC_UPLOAD_ID ON INVENTORY_SUCCESS_RECORDS (UPLOAD_ID);

-- ─── INVENTORY_FAILURE_RECORDS ────────────────────────────────────────────────

CREATE TABLE INVENTORY_FAILURE_RECORDS (
  ID                    NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  UPLOAD_ID             NUMBER(10)    NOT NULL,
  ROW_NUMBER            NUMBER(10)    NOT NULL,
  RAW_DATA              CLOB,
  ERROR_MESSAGE         CLOB,
  RESPONSE_BODY         CLOB,
  RESPONSE_STATUS       NUMBER(10),
  ORACLE_ERROR_CODE     VARCHAR2(200),
  ORACLE_PROCESS_STATUS VARCHAR2(50),
  CREATED_AT            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INVFAIL_UPLOAD FOREIGN KEY (UPLOAD_ID) REFERENCES INVENTORY_UPLOADS (ID)
);

CREATE INDEX IDX_INVFAIL_UPLOAD_ID ON INVENTORY_FAILURE_RECORDS (UPLOAD_ID);

-- ─── MISC_RECEIPT_UPLOADS ─────────────────────────────────────────────────────

CREATE TABLE MISC_RECEIPT_UPLOADS (
  ID               NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID          NUMBER(10)    NOT NULL,
  FILENAME         VARCHAR2(500) NOT NULL,
  XML_PAYLOAD      CLOB,
  TOTAL_RECORDS    NUMBER(10)    DEFAULT 0 NOT NULL,
  SUCCESS_COUNT    NUMBER(10)    DEFAULT 0 NOT NULL,
  FAILURE_COUNT    NUMBER(10)    DEFAULT 0 NOT NULL,
  RESPONSE_STATUS  VARCHAR2(100),
  RESPONSE_MESSAGE CLOB,
  RESPONSE_LOG     CLOB,
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_MISCUP_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_MISCUP_USER_ID ON MISC_RECEIPT_UPLOADS (USER_ID);
CREATE INDEX IDX_MISCUP_CREATED ON MISC_RECEIPT_UPLOADS (CREATED_AT);

-- ─── MISC_RECEIPT_FAILURES ────────────────────────────────────────────────────

CREATE TABLE MISC_RECEIPT_FAILURES (
  ID               NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  UPLOAD_ID        NUMBER(10)    NOT NULL,
  ROW_NUMBER       NUMBER(10)    NOT NULL,
  RAW_DATA         CLOB,
  ERROR_MESSAGE    CLOB,
  REQUEST_PAYLOAD  CLOB,
  RESPONSE_BODY    CLOB,
  RESPONSE_STATUS  NUMBER(10),
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_MISCFAIL_UPLOAD FOREIGN KEY (UPLOAD_ID) REFERENCES MISC_RECEIPT_UPLOADS (ID)
);

CREATE INDEX IDX_MISCFAIL_UPLOAD_ID ON MISC_RECEIPT_FAILURES (UPLOAD_ID);

-- ─── STANDARD_RECEIPT_UPLOADS ─────────────────────────────────────────────────

CREATE TABLE STANDARD_RECEIPT_UPLOADS (
  ID               NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID          NUMBER(10)    NOT NULL,
  FILENAME         VARCHAR2(500) NOT NULL,
  PAYLOAD_JSON     CLOB,
  TOTAL_RECORDS    NUMBER(10)    DEFAULT 0          NOT NULL,
  SUCCESS_COUNT    NUMBER(10)    DEFAULT 0          NOT NULL,
  FAILURE_COUNT    NUMBER(10)    DEFAULT 0          NOT NULL,
  STATUS           VARCHAR2(50)  DEFAULT 'PROCESSING' NOT NULL,
  RESPONSE_MESSAGE CLOB,
  RESPONSE_LOG     CLOB,
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_STDUP_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_STDUP_USER_ID ON STANDARD_RECEIPT_UPLOADS (USER_ID);
CREATE INDEX IDX_STDUP_STATUS  ON STANDARD_RECEIPT_UPLOADS (STATUS);
CREATE INDEX IDX_STDUP_CREATED ON STANDARD_RECEIPT_UPLOADS (CREATED_AT);

-- ─── STANDARD_RECEIPT_FAILURES ────────────────────────────────────────────────

CREATE TABLE STANDARD_RECEIPT_FAILURES (
  ID               NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  UPLOAD_ID        NUMBER(10)    NOT NULL,
  ROW_NUMBER       NUMBER(10)    NOT NULL,
  RAW_DATA         CLOB,
  ERROR_MESSAGE    CLOB,
  REQUEST_PAYLOAD  CLOB,
  RESPONSE_BODY    CLOB,
  RESPONSE_STATUS  NUMBER(10),
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_STDFAIL_UPLOAD FOREIGN KEY (UPLOAD_ID)
    REFERENCES STANDARD_RECEIPT_UPLOADS (ID)
);

CREATE INDEX IDX_STDFAIL_UPLOAD_ID ON STANDARD_RECEIPT_FAILURES (UPLOAD_ID);

-- ─── APPLY_RECEIPT_UPLOADS ────────────────────────────────────────────────────

CREATE TABLE APPLY_RECEIPT_UPLOADS (
  ID               NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID          NUMBER(10)    NOT NULL,
  FILENAME         VARCHAR2(500) NOT NULL,
  TOTAL_RECORDS    NUMBER(10)    DEFAULT 0           NOT NULL,
  TOTAL_RECEIPTS   NUMBER(10)    DEFAULT 0           NOT NULL,
  SUCCESS_COUNT    NUMBER(10)    DEFAULT 0           NOT NULL,
  FAILURE_COUNT    NUMBER(10)    DEFAULT 0           NOT NULL,
  STATUS           VARCHAR2(50)  DEFAULT 'PROCESSING' NOT NULL,
  RESPONSE_MESSAGE CLOB,
  RESPONSE_LOG     CLOB,
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_APPUP_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_APPUP_USER_ID ON APPLY_RECEIPT_UPLOADS (USER_ID);
CREATE INDEX IDX_APPUP_STATUS  ON APPLY_RECEIPT_UPLOADS (STATUS);
CREATE INDEX IDX_APPUP_CREATED ON APPLY_RECEIPT_UPLOADS (CREATED_AT);

-- ─── APPLY_RECEIPT_FAILURES ───────────────────────────────────────────────────

CREATE TABLE APPLY_RECEIPT_FAILURES (
  ID               NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  UPLOAD_ID        NUMBER(10)    NOT NULL,
  ROW_NUMBER       NUMBER(10)    NOT NULL,
  INVOICE_NUMBER   VARCHAR2(500),
  RECEIPT_NUMBER   VARCHAR2(500),
  ERROR_MESSAGE    CLOB,
  ERROR_STEP       VARCHAR2(100),
  REQUEST_PAYLOAD  CLOB,
  RESPONSE_BODY    CLOB,
  RESPONSE_STATUS  NUMBER(10),
  CUSTOMER_TRX_ID  VARCHAR2(200),
  RECEIPT_ID       VARCHAR2(200),
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_APPFAIL_UPLOAD FOREIGN KEY (UPLOAD_ID)
    REFERENCES APPLY_RECEIPT_UPLOADS (ID)
);

CREATE INDEX IDX_APPFAIL_UPLOAD_ID ON APPLY_RECEIPT_FAILURES (UPLOAD_ID);

-- ─── AR_INVOICE_UPLOADS ───────────────────────────────────────────────────────

CREATE TABLE AR_INVOICE_UPLOADS (
  ID               NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID          NUMBER(10)    NOT NULL,
  PAYLOAD_JSON     CLOB,
  RESPONSE_STATUS  VARCHAR2(100),
  RESPONSE_MESSAGE CLOB,
  RESPONSE_BODY    CLOB,
  HTTP_STATUS      NUMBER(10),
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_ARINVUP_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_ARINVUP_USER_ID ON AR_INVOICE_UPLOADS (USER_ID);
CREATE INDEX IDX_ARINVUP_CREATED ON AR_INVOICE_UPLOADS (CREATED_AT);

-- ─── FUSION_SALES_METADATA ────────────────────────────────────────────────────

CREATE TABLE FUSION_SALES_METADATA (
  ID                    NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROW_ID                NUMBER(10)    NOT NULL,
  BILL_TO_NAME          VARCHAR2(500) NOT NULL,
  BILL_TO_ACCOUNT       NUMBER(10)    NOT NULL,
  SITE_NUMBER           VARCHAR2(200),
  BUSINESS_UNIT         VARCHAR2(200),
  TXN_SOURCE            VARCHAR2(200),
  TXN_TYPE              VARCHAR2(200),
  RATE_IS_CORPORATE     VARCHAR2(50),
  REC_ACTIVITY_NAME_BANK VARCHAR2(200),
  SUBINVENTORY          VARCHAR2(200),
  INTEGRATION_SOURCE    VARCHAR2(200),
  DISTRIBUTION_ACC_ID   VARCHAR2(200),
  REC_ACTIVITY_NAME_CASH VARCHAR2(200),
  REGION                VARCHAR2(50),
  CUSTOMER_TYPE         VARCHAR2(100),
  COST_CENTER_CODE      VARCHAR2(100),
  CREATED_AT            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_FSM_ROW_ID UNIQUE (ROW_ID)
);

CREATE OR REPLACE TRIGGER TRG_FSM_UPD
  BEFORE UPDATE ON FUSION_SALES_METADATA FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

CREATE INDEX IDX_FSM_BILL_TO_SUBINV ON FUSION_SALES_METADATA (BILL_TO_NAME, SUBINVENTORY);
CREATE INDEX IDX_FSM_SUBINV         ON FUSION_SALES_METADATA (SUBINVENTORY);
CREATE INDEX IDX_FSM_CUSTOMER_TYPE  ON FUSION_SALES_METADATA (CUSTOMER_TYPE);

-- ─── AR_INVOICE_DATA ──────────────────────────────────────────────────────────

CREATE TABLE AR_INVOICE_DATA (
  ID                       NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_NAME            VARCHAR2(500) NOT NULL,
  CUSTOMER_NUMBER          VARCHAR2(200),
  SITE_NUMBER              VARCHAR2(200),
  SUBINVENTORY             VARCHAR2(200),
  BUSINESS_UNIT            VARCHAR2(200),
  TRANSACTION_SOURCE       VARCHAR2(200),
  TRANSACTION_TYPE         VARCHAR2(200),
  TRANSACTION_DATE         VARCHAR2(30),
  ACCOUNTING_DATE          VARCHAR2(30),
  PAYMENT_TERMS            VARCHAR2(200),
  INVOICE_CURRENCY_CODE    VARCHAR2(10),
  CROSS_REFERENCE          VARCHAR2(500),
  COMMENTS                 CLOB,
  LINE_NUMBER              NUMBER(10),
  ITEM_NUMBER              VARCHAR2(200),
  DESCRIPTION              CLOB,
  QUANTITY                 NUMBER(18,4),
  UNIT_SELLING_PRICE       NUMBER(18,4),
  TAX_CLASSIFICATION_CODE  VARCHAR2(200),
  SALES_ORDER              VARCHAR2(200),
  MEMO_LINE                VARCHAR2(500),
  USER_ID                  NUMBER(10)    NOT NULL,
  UPLOAD_BATCH_ID          VARCHAR2(200),
  STATUS                   VARCHAR2(50)  DEFAULT 'PENDING' NOT NULL,
  PROCESSED_AT             TIMESTAMP,
  CREATED_AT               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT               TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_ARINVDATA_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE OR REPLACE TRIGGER TRG_ARINVDATA_UPD
  BEFORE UPDATE ON AR_INVOICE_DATA FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

CREATE INDEX IDX_ARINVDATA_CUST_SUBINV  ON AR_INVOICE_DATA (CUSTOMER_NAME, SUBINVENTORY);
CREATE INDEX IDX_ARINVDATA_BATCH_ID     ON AR_INVOICE_DATA (UPLOAD_BATCH_ID);
CREATE INDEX IDX_ARINVDATA_STATUS       ON AR_INVOICE_DATA (STATUS);
CREATE INDEX IDX_ARINVDATA_USER_ID      ON AR_INVOICE_DATA (USER_ID);

-- ─── FUSION_INVOICE_HEADERS ───────────────────────────────────────────────────

CREATE TABLE FUSION_INVOICE_HEADERS (
  ID                  NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROW_ID              NUMBER(10),
  REQUEST_ID          NUMBER(10),
  STATUS              VARCHAR2(100),
  MESSAGE             CLOB,
  REQUEST_DATE        TIMESTAMP,
  BILL_TO_CUST_NAME   VARCHAR2(500),
  BILL_TO_LOCATION    VARCHAR2(500),
  BILL_TO_ACC_NUMBER  NUMBER(10),
  BUSINESS_UNIT       VARCHAR2(200),
  PAYMENT_TERMS_NAME  VARCHAR2(200),
  TXN_SOURCE          VARCHAR2(200),
  TXN_TYPE            VARCHAR2(200),
  TXN_DATE            TIMESTAMP,
  GL_DATE             TIMESTAMP,
  CURRENCY_CODE       VARCHAR2(10),
  TXN_NUMBER          NUMBER(10),
  CUSTOMER_TXN_ID     NUMBER(10),
  REGION              VARCHAR2(50),
  CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE OR REPLACE TRIGGER TRG_FUSINVHDR_UPD
  BEFORE UPDATE ON FUSION_INVOICE_HEADERS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

CREATE INDEX IDX_FUSINVHDR_STATUS    ON FUSION_INVOICE_HEADERS (STATUS);
CREATE INDEX IDX_FUSINVHDR_REQ_ID    ON FUSION_INVOICE_HEADERS (REQUEST_ID);
CREATE INDEX IDX_FUSINVHDR_TXN_NUM   ON FUSION_INVOICE_HEADERS (TXN_NUMBER);

-- ─── FUSION_INVOICE_LINES ─────────────────────────────────────────────────────

CREATE TABLE FUSION_INVOICE_LINES (
  ID                  NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROW_ID              NUMBER(10),
  REQUEST_ID          NUMBER(10),
  STATUS              VARCHAR2(100),
  MESSAGE             CLOB,
  REQUEST_DATE        TIMESTAMP,
  INVOICE_NUMBER      VARCHAR2(200),
  LINE_NUMBER         NUMBER(10),
  ITEM_NUMBER         VARCHAR2(200),
  DESCRIPTION         CLOB,
  UOM                 VARCHAR2(50),
  QUANTITY            NUMBER(18,4),
  UNIT_SELLING_PRICE  NUMBER(18,4),
  CURRENCY_CODE       VARCHAR2(10),
  TAX_CODE            VARCHAR2(200),
  VERSION             NUMBER(10),
  SALES_ORDER         VARCHAR2(200),
  SALES_ORDER_LINE    NUMBER(10),
  REGION              VARCHAR2(50),
  HEADER_ID           NUMBER(10),
  CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_FUSINVLINE_HDR FOREIGN KEY (HEADER_ID)
    REFERENCES FUSION_INVOICE_HEADERS (ID)
);

CREATE OR REPLACE TRIGGER TRG_FUSINVLINE_UPD
  BEFORE UPDATE ON FUSION_INVOICE_LINES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

CREATE INDEX IDX_FUSINVLINE_STATUS      ON FUSION_INVOICE_LINES (STATUS);
CREATE INDEX IDX_FUSINVLINE_REQ_ID      ON FUSION_INVOICE_LINES (REQUEST_ID);
CREATE INDEX IDX_FUSINVLINE_INV_NUM     ON FUSION_INVOICE_LINES (INVOICE_NUMBER);
CREATE INDEX IDX_FUSINVLINE_SALES_ORD   ON FUSION_INVOICE_LINES (SALES_ORDER);
CREATE INDEX IDX_FUSINVLINE_HEADER_ID   ON FUSION_INVOICE_LINES (HEADER_ID);

-- ─── FUSION_RECEIPT_METHODS ───────────────────────────────────────────────────

CREATE TABLE FUSION_RECEIPT_METHODS (
  ID                  NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROW_ID              NUMBER(10),
  RECEIPT_METHOD_ID   VARCHAR2(100) NOT NULL,
  RECEIPT_METHOD_NAME VARCHAR2(200),
  RECEIPT_IS_CASH     NUMBER(1)     DEFAULT 0 NOT NULL,
  RECEIPT_BANK_CHARGE NUMBER(18,4)  DEFAULT 0 NOT NULL,
  RECEIPT_METHOD_TAX  NUMBER(18,4)  DEFAULT 0 NOT NULL,
  REGION              VARCHAR2(50)  NOT NULL,
  CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_FRM_IS_CASH CHECK (RECEIPT_IS_CASH IN (0, 1))
);

CREATE INDEX IDX_FRM_NAME_REGION ON FUSION_RECEIPT_METHODS (RECEIPT_METHOD_NAME, REGION);
CREATE INDEX IDX_FRM_REGION      ON FUSION_RECEIPT_METHODS (REGION);

-- ─── VENDHQ_REGISTERS ─────────────────────────────────────────────────────────

CREATE TABLE VENDHQ_REGISTERS (
  ID               NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REGISTER_ID      VARCHAR2(200) NOT NULL,
  OUTLET_ID        VARCHAR2(200),
  REGISTER_NAME    VARCHAR2(200),
  CASH_ACCOUNT     VARCHAR2(500),
  CASH_ACCOUNT_ID  VARCHAR2(200),
  BANK_ACCOUNT     VARCHAR2(500),
  BANK_ACCOUNT_ID  VARCHAR2(200),
  VERSION          VARCHAR2(50),
  DELETED_AT       VARCHAR2(100),
  REGION           VARCHAR2(50),
  GIFT_ACCOUNT     VARCHAR2(500),
  GIFT_ACCOUNT_ID  VARCHAR2(200),
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT UQ_VENDHQ_REG_ID UNIQUE (REGISTER_ID)
);

CREATE INDEX IDX_VENDHQ_REG_NAME ON VENDHQ_REGISTERS (REGISTER_NAME);
CREATE INDEX IDX_VENDHQ_REGION   ON VENDHQ_REGISTERS (REGION);

-- ─── FUSION_STANDARD_RECEIPTS ─────────────────────────────────────────────────

CREATE TABLE FUSION_STANDARD_RECEIPTS (
  ID                   NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROW_ID               NUMBER(10),
  REQUEST_ID           NUMBER(10),
  STATUS               VARCHAR2(100),
  MESSAGE              CLOB,
  REQUEST_DATE         TIMESTAMP,
  CURRENCY_CODE        VARCHAR2(10),
  RECEIPT_DATE         TIMESTAMP,
  GL_DATE              TIMESTAMP,
  EXCHANGE_DATE        TIMESTAMP,
  EXCHANGE_RATE_TYPE   VARCHAR2(100),
  RECEIPT_METHOD_ID    VARCHAR2(100),
  RECEIPT_NUMBER       VARCHAR2(200),
  REMITTANCE_BANK_ACC_ID VARCHAR2(200),
  DEPOSIT_DATE         TIMESTAMP,
  CUSTOMER_ID          VARCHAR2(200),
  ORG_ID               VARCHAR2(200),
  AMOUNT               NUMBER(18,4),
  REGION               VARCHAR2(50),
  INTEG_MODE           VARCHAR2(50),
  BATCH_ID             NUMBER(10),
  CREATED_AT           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_FUSSTDREC_RECEIPT_NUM ON FUSION_STANDARD_RECEIPTS (RECEIPT_NUMBER);
CREATE INDEX IDX_FUSSTDREC_STATUS      ON FUSION_STANDARD_RECEIPTS (STATUS);
CREATE INDEX IDX_FUSSTDREC_REQ_ID      ON FUSION_STANDARD_RECEIPTS (REQUEST_ID);
CREATE INDEX IDX_FUSSTDREC_BATCH_ID    ON FUSION_STANDARD_RECEIPTS (BATCH_ID);

-- ─── FUSION_MISC_RECEIPTS ─────────────────────────────────────────────────────

CREATE TABLE FUSION_MISC_RECEIPTS (
  ID                  NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROW_ID              NUMBER(10),
  REQUEST_ID          NUMBER(10),
  STATUS              VARCHAR2(100),
  MESSAGE             CLOB,
  REQUEST_DATE        TIMESTAMP,
  CURRENCY_CODE       VARCHAR2(10),
  GL_DATE             TIMESTAMP,
  EXCHANGE_DATE       TIMESTAMP,
  EXCHANGE_RATE_TYPE  VARCHAR2(100),
  RECEIPT_METHOD_NAME VARCHAR2(200),
  RECEIPT_NUMBER      VARCHAR2(200),
  BANK_ACC_NUMBER     VARCHAR2(500),
  REC_ACTIVITY_NAME   VARCHAR2(200),
  AMOUNT              NUMBER(18,4),
  RECEIPT_DATE        TIMESTAMP,
  REGION              VARCHAR2(50),
  INTEG_MODE          VARCHAR2(50),
  BATCH_ID            NUMBER(10),
  CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_FUSMISCREC_RECEIPT_NUM ON FUSION_MISC_RECEIPTS (RECEIPT_NUMBER);
CREATE INDEX IDX_FUSMISCREC_STATUS      ON FUSION_MISC_RECEIPTS (STATUS);
CREATE INDEX IDX_FUSMISCREC_REQ_ID      ON FUSION_MISC_RECEIPTS (REQUEST_ID);
CREATE INDEX IDX_FUSMISCREC_BATCH_ID    ON FUSION_MISC_RECEIPTS (BATCH_ID);

-- ─── FUSION_APPLY_RECEIPTS ────────────────────────────────────────────────────

CREATE TABLE FUSION_APPLY_RECEIPTS (
  ID               NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ROW_ID           NUMBER(10),
  REQUEST_ID       NUMBER(10),
  STATUS           VARCHAR2(100),
  MESSAGE          CLOB,
  REQUEST_DATE     TIMESTAMP,
  ACCOUNTING_DATE  TIMESTAMP,
  APPLICATION_DATE TIMESTAMP,
  TXN_NUMBER       VARCHAR2(200),
  RECEIPT_NUMBER   VARCHAR2(200),
  AMOUNT_APPLIED   NUMBER(18,4),
  CURRENCY_CODE    VARCHAR2(10),
  REGION           VARCHAR2(50),
  INTEG_MODE       VARCHAR2(50),
  TXN_SOURCE       VARCHAR2(200),
  BATCH_ID         NUMBER(10),
  CREATED_AT       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_FUSAPPREC_RECEIPT_NUM ON FUSION_APPLY_RECEIPTS (RECEIPT_NUMBER);
CREATE INDEX IDX_FUSAPPREC_TXN_NUM     ON FUSION_APPLY_RECEIPTS (TXN_NUMBER);
CREATE INDEX IDX_FUSAPPREC_STATUS      ON FUSION_APPLY_RECEIPTS (STATUS);
CREATE INDEX IDX_FUSAPPREC_REQ_ID      ON FUSION_APPLY_RECEIPTS (REQUEST_ID);
CREATE INDEX IDX_FUSAPPREC_BATCH_ID    ON FUSION_APPLY_RECEIPTS (BATCH_ID);

-- ─── VEND_RECEIPT_BATCHES ─────────────────────────────────────────────────────

CREATE TABLE VEND_RECEIPT_BATCHES (
  ID                NUMBER(10)    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID           NUMBER(10)    NOT NULL,
  FILENAME          VARCHAR2(500) NOT NULL,
  REGION            VARCHAR2(10)  DEFAULT 'SA'          NOT NULL,
  TOTAL_STANDARD    NUMBER(10)    DEFAULT 0             NOT NULL,
  TOTAL_MISC        NUMBER(10)    DEFAULT 0             NOT NULL,
  SUCCESS_STANDARD  NUMBER(10)    DEFAULT 0             NOT NULL,
  FAILURE_STANDARD  NUMBER(10)    DEFAULT 0             NOT NULL,
  SUCCESS_MISC      NUMBER(10)    DEFAULT 0             NOT NULL,
  FAILURE_MISC      NUMBER(10)    DEFAULT 0             NOT NULL,
  STATUS            VARCHAR2(50)  DEFAULT 'GENERATED'   NOT NULL,
  PAYLOADS_JSON     CLOB,
  RESPONSE_LOG      CLOB,
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP  NOT NULL,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP  NOT NULL,
  CONSTRAINT FK_VENDBATCH_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE OR REPLACE TRIGGER TRG_VENDBATCH_UPD
  BEFORE UPDATE ON VEND_RECEIPT_BATCHES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

CREATE INDEX IDX_VENDBATCH_STATUS  ON VEND_RECEIPT_BATCHES (STATUS);
CREATE INDEX IDX_VENDBATCH_USER_ID ON VEND_RECEIPT_BATCHES (USER_ID);

-- =============================================================================
-- End of schema
-- =============================================================================
